spring.application.name=OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23lilnhQMe0SghPPvi
spring.security.oauth2.client.registration.github.client-secret=5c6440965e4ec16a1f3d25150a0b5c1e81178d7e
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id
server.port=8080
